name: staffplugin1.13
version: '${project.version}'
main: org.kamshi.staffplugin1.Staffplugin1
api-version: '1.13'
commands:
  tag:
    description: Ustawia lub resetuje tag gracza
    usage: /tag <gracz> <tag|reset>
  mute:
    description: Wyciszenie gracza na stałe.
    usage: /mute <gracz> [powód]
    permission-message: "Nie masz uprawnień do wyciszenia graczy."
    permission: staff.mute
  tempmute:
    description: Tymczasowe wyciszenie gracza.
    usage: /tempmute <gracz> <czas> [powód]
    permission-message: "Nie masz uprawnień do tymczasowego wyciszenia graczy."
    permission: staff.tempmute
  unmute:
    description: Odciszenie gracza.
    usage: /unmute <gracz>
    permission-message: "Nie masz uprawnień do odciszenia graczy."
    permission: staff.unmute
  tempban:
    description: Tymczasowe banowanie graczy.
    usage: /tempban <gracz> <czas> [powód]
    permission: staff.tempban
  ban:
    description: Banuje gracza
    usage: /ban <gracz> [powód]
    permission: staff.ban
  unban:
    description: Odbanowuje gracza
    usage: /unban <gracz>
    permission: staff.unban
  jqmessage:
    description: Włącza lub wyłącza niestandardową wiadomość powitalną
    usage: /jqmessage
    permission: staff.jqmsg
  heal:
    description: Heal yourself or a specified player
    usage: /heal [player]
    permission: staff.heal.use
  speed:
    description: Set your walking or flying speed
    usage: /speed <1-10>
    permission: staff.speed.use
  god:
    description: Toggle GodMode on or off for a player
    usage: /god
    permission: staff.godmode
  wielkichlop:
    description: Toggle GodMode on or off for a player
    usage: /godmode
    permission: staff.wielkichlop
  malychlop:
    description: Toggle GodMode on or off for a player
    usage: /godmode
    permission: staff.malychlop
  staffplugin:
    description: StaffPlugin commands.
    usage: /staffplugin help
    permission: staff.help.use
    permission-message: You do not have permission to use this command.
  freeze:
    description: Zablokuj lub odblokuj gracza.
    usage: /freeze <gracz>
    permission: staff.freeze
  fly:
    description: Toggles fly mode for the player.
    usage: /fly
    permission: staff.fly.use
    permission-message: You do not have permission to use this command.
  gm:
    description: Change your game mode
    usage: /gm <mode>
    permission: staff.gm.use
  tphere:
    description: Teleportuje wskazanego gracza do ciebie
    usage: /tphere <gracz>
    permission: staff.tphere.use
  vanish:
    description: Toggle vanish mode
    aliases: [v]
    usage: /vanish
    permission: staff.vanish.use
    permission-message: You do not have permission to use this command.
  tp:
    description: Teleport to another player
    usage: /tp <player>
    permission: staff.teleport.use
    permission-message: "Nie posiadasz permisji do użycia tej komendy."
permissions:
  staff.ban:
    description: Allows the player to set their speed
    default: op
  staff.unban:
    description: Allows the player to set their speed
    default: op
  staff.tempban:
    description: Allows the player to set their speed
    default: op
  staff.mute:
    description: Allows the player to set their speed
    default: op
  staff.unmute:
    description: Allows the player to set their speed
    default: op
  staff.tempmute:
      description: Allows the player to set their speed
      default: op
  staff.speed.use:
    description: Allows the player to set their speed
    default: op
  staff.godmode:
    description: Allows the player to toggle GodMode
    default: op
  staff.wielkichlop:
    description: Allows the player to toggle GodMode
    default: op
  staff.malychlop:
    description: Allows the player to toggle GodMode
    default: op
  staff.vanish.use:
    description: Allows the player to use the vanish command
    default: op
  staff.vanish.see:
    description: Allows the player to see vanished players
    default: op
  staff.heal.use:
    description: Allows use of the heal command
    default: op
  staff.freeze:
    description: Pozwól na używanie komendy /freeze.
    default: op
  staff.teleport.use:
    description: Pozwól na używanie komendy /tp.
    default: op
  staff.joinmsg:
    description: Pozwól na używanie komendy /tp.
    default: op
